function execute() {
    return Response.success([
        {title: "4 koma", input: "/genres/4-koma/{0}", script: "cat.js"},
        {title: "Action", input: "/genres/action/{0}", script: "cat.js"},
        {title: "Adaptation", input: "/genres/adaptation/{0}", script: "cat.js"},
        {title: "Adventure", input: "/genres/adventure/{0}", script: "cat.js"},
        {title: "Aliens", input: "/genres/aliens/{0}", script: "cat.js"},
        {title: "All Ages", input: "/genres/all-ages/{0}", script: "cat.js"},
        {title: "Animals", input: "/genres/animals/{0}", script: "cat.js"},
        {title: "Anthology", input: "/genres/anthology/{0}", script: "cat.js"},
        {title: "Award winning", input: "/genres/award-winning/{0}", script: "cat.js"},
        {title: "bara", input: "/genres/bara/{0}", script: "cat.js"},
        {title: "Cars", input: "/genres/cars/{0}", script: "cat.js"},
        {title: "Chinese", input: "/genres/chinese/{0}", script: "cat.js"},
        {title: "Chinese (Traditional)", input: "/genres/chinese-traditional/{0}", script: "cat.js"},
        {title: "Comedy", input: "/genres/comedy/{0}", script: "cat.js"},
        {title: "Comic", input: "/genres/comic/{0}", script: "cat.js"},
        {title: "Cooking", input: "/genres/cooking/{0}", script: "cat.js"},
        {title: "Crime", input: "/genres/crime/{0}", script: "cat.js"},
        {title: "Crossdressing", input: "/genres/crossdressing/{0}", script: "cat.js"},
        {title: "Delinquents", input: "/genres/delinquents/{0}", script: "cat.js"},
        {title: "Dementia", input: "/genres/dementia/{0}", script: "cat.js"},
        {title: "Demons", input: "/genres/demons/{0}", script: "cat.js"},
        {title: "Doujinshi", input: "/genres/doujinshi/{0}", script: "cat.js"},
        {title: "Drama", input: "/genres/drama/{0}", script: "cat.js"},
        {title: "Ecchi", input: "/genres/ecchi/{0}", script: "cat.js"},
        {title: "English", input: "/genres/english/{0}", script: "cat.js"},
        {title: "Fan colored", input: "/genres/fan-colored/{0}", script: "cat.js"},
        {title: "Fantasy", input: "/genres/fantasy/{0}", script: "cat.js"},
        {title: "Full color", input: "/genres/full-color/{0}", script: "cat.js"},
        {title: "Game", input: "/genres/game/{0}", script: "cat.js"},
        {title: "Gender Bender", input: "/genres/gender-bender/{0}", script: "cat.js"},
        {title: "Ghosts", input: "/genres/ghosts/{0}", script: "cat.js"},
        {title: "Gore", input: "/genres/gore/{0}", script: "cat.js"},
        {title: "Gossip", input: "/genres/gossip/{0}", script: "cat.js"},
        {title: "Gyaru", input: "/genres/gyaru/{0}", script: "cat.js"},
        {title: "Harem", input: "/genres/harem/{0}", script: "cat.js"},
        {title: "Historical", input: "/genres/historical/{0}", script: "cat.js"},
        {title: "Horror", input: "/genres/horror/{0}", script: "cat.js"},
        {title: "Incest", input: "/genres/incest/{0}", script: "cat.js"},
        {title: "Isekai", input: "/genres/isekai/{0}", script: "cat.js"},
        {title: "Japanese", input: "/genres/japanese/{0}", script: "cat.js"},
        {title: "Josei", input: "/genres/josei/{0}", script: "cat.js"},
        {title: "Kids", input: "/genres/kids/{0}", script: "cat.js"},
        {title: "Long strip", input: "/genres/long-strip/{0}", script: "cat.js"},
        {title: "Mafia", input: "/genres/mafia/{0}", script: "cat.js"},
        {title: "Magic", input: "/genres/magic/{0}", script: "cat.js"},
        {title: "Magical girls", input: "/genres/magical-girls/{0}", script: "cat.js"},
        {title: "Manga", input: "/genres/manga/{0}", script: "cat.js"},
        {title: "Manhua", input: "/genres/manhua/{0}", script: "cat.js"},
        {title: "Manhwa", input: "/genres/manhwa/{0}", script: "cat.js"},
        {title: "Martial Arts", input: "/genres/martial-arts/{0}", script: "cat.js"},
        {title: "Mature", input: "/genres/mature/{0}", script: "cat.js"},
        {title: "Mecha", input: "/genres/mecha/{0}", script: "cat.js"},
        {title: "Medical", input: "/genres/medical/{0}", script: "cat.js"},
        {title: "Military", input: "/genres/military/{0}", script: "cat.js"},
        {title: "Monster girls", input: "/genres/monster-girls/{0}", script: "cat.js"},
        {title: "Monsters", input: "/genres/monsters/{0}", script: "cat.js"},
        {title: "Music", input: "/genres/music/{0}", script: "cat.js"},
        {title: "Mystery", input: "/genres/mystery/{0}", script: "cat.js"},
        {title: "Ninja", input: "/genres/ninja/{0}", script: "cat.js"},
        {title: "NOVEL", input: "/genres/novel/{0}", script: "cat.js"},
        {title: "NTR", input: "/genres/ntr/{0}", script: "cat.js"},
        {title: "Office", input: "/genres/office/{0}", script: "cat.js"},
        {title: "Office workers", input: "/genres/office-workers/{0}", script: "cat.js"},
        {title: "Official colored", input: "/genres/official-colored/{0}", script: "cat.js"},
        {title: "One shot", input: "/genres/one-shot/{0}", script: "cat.js"},
        {title: "Parody", input: "/genres/parody/{0}", script: "cat.js"},
        {title: "Philosophical", input: "/genres/philosophical/{0}", script: "cat.js"},
        {title: "Police", input: "/genres/police/{0}", script: "cat.js"},
        {title: "Post apocalyptic", input: "/genres/post-apocalyptic/{0}", script: "cat.js"},
        {title: "Psychological", input: "/genres/psychological/{0}", script: "cat.js"},
        {title: "Reincarnation", input: "/genres/reincarnation/{0}", script: "cat.js"},
        {title: "Reverse harem", input: "/genres/reverse-harem/{0}", script: "cat.js"},
        {title: "Romance", input: "/genres/romance/{0}", script: "cat.js"},
        {title: "Samurai", input: "/genres/samurai/{0}", script: "cat.js"},
        {title: "School life", input: "/genres/school-life/{0}", script: "cat.js"},
        {title: "Science fiction", input: "/genres/science-fiction/{0}", script: "cat.js"},
        {title: "Seinen", input: "/genres/seinen/{0}", script: "cat.js"},
        {title: "Sexual violence", input: "/genres/sexual-violence/{0}", script: "cat.js"},
        {title: "Shoujo", input: "/genres/shoujo/{0}", script: "cat.js"},
        {title: "Shoujo Ai", input: "/genres/shoujo-ai/{0}", script: "cat.js"},
        {title: "Shounen", input: "/genres/shounen/{0}", script: "cat.js"},
        {title: "Shounen Ai", input: "/genres/shounen-ai/{0}", script: "cat.js"},
        {title: "Slice of Life", input: "/genres/slice-of-life/{0}", script: "cat.js"},
        {title: "Smut", input: "/genres/smut/{0}", script: "cat.js"},
        {title: "Space", input: "/genres/space/{0}", script: "cat.js"},
        {title: "Sports", input: "/genres/sports/{0}", script: "cat.js"},
        {title: "Super Power", input: "/genres/super-power/{0}", script: "cat.js"},
        {title: "Superhero", input: "/genres/superhero/{0}", script: "cat.js"},
        {title: "Supernatural", input: "/genres/supernatural/{0}", script: "cat.js"},
        {title: "Survival", input: "/genres/survival/{0}", script: "cat.js"},
        {title: "Thriller", input: "/genres/thriller/{0}", script: "cat.js"},
        {title: "Time travel", input: "/genres/time-travel/{0}", script: "cat.js"},
        {title: "Toomics", input: "/genres/toomics/{0}", script: "cat.js"},
        {title: "Traditional games", input: "/genres/traditional-games/{0}", script: "cat.js"},
        {title: "Tragedy", input: "/genres/tragedy/{0}", script: "cat.js"},
        {title: "Uncategorized", input: "/genres/uncategorized/{0}", script: "cat.js"},
        {title: "Uncensored", input: "/genres/uncensored/{0}", script: "cat.js"},
        {title: "User created", input: "/genres/user-created/{0}", script: "cat.js"},
        {title: "Vampires", input: "/genres/vampires/{0}", script: "cat.js"},
        {title: "Vanilla", input: "/genres/vanilla/{0}", script: "cat.js"},
        {title: "Video games", input: "/genres/video-games/{0}", script: "cat.js"},
        {title: "Villainess", input: "/genres/villainess/{0}", script: "cat.js"},
        {title: "Virtual reality", input: "/genres/virtual-reality/{0}", script: "cat.js"},
        {title: "Web comic", input: "/genres/web-comic/{0}", script: "cat.js"},
        {title: "Webtoon", input: "/genres/webtoon/{0}", script: "cat.js"},
        {title: "Wuxia", input: "/genres/wuxia/{0}", script: "cat.js"},
        {title: "Yaoi", input: "/genres/yaoi/{0}", script: "cat.js"},
        {title: "Yuri", input: "/genres/yuri/{0}", script: "cat.js"},
        {title: "Zombies", input: "/genres/zombies/{0}", script: "cat.js"},
    ])
}

// console.log([...document.querySelectorAll('.dropdown-menu .multi-column-dropdown li > a')].map(e => `{title: "${e.innerText.trim()}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '') + '/{0}'}", script: "cat.js"},`).join('\n'));