function execute() {
    return Response.success([
        {title: "Action", input: "/manga-list/action/{0}/", script: "gen.js"},
        {title: "Mecha", input: "/manga-list/mecha/{0}/", script: "gen.js"},
        {title: "18+", input: "/manga-list/18/{0}/", script: "gen.js"},
        {title: "Mystery", input: "/manga-list/mystery/{0}/", script: "gen.js"},
        {title: "Adult", input: "/manga-list/adult/{0}/", script: "gen.js"},
        {title: "One shot", input: "/manga-list/one-shot/{0}/", script: "gen.js"},
        {title: "Anime", input: "/manga-list/anime/{0}/", script: "gen.js"},
        {title: "Psychological", input: "/manga-list/psychological/{0}/", script: "gen.js"},
        {title: "Comedy", input: "/manga-list/comedy/{0}/", script: "gen.js"},
        {title: "Romance", input: "/manga-list/romance/{0}/", script: "gen.js"},
        {title: "Comic", input: "/manga-list/comic/{0}/", script: "gen.js"},
        {title: "School Life", input: "/manga-list/school-life/{0}/", script: "gen.js"},
        {title: "Doujinshi", input: "/manga-list/doujinshi/{0}/", script: "gen.js"},
        {title: "Sci-fi", input: "/manga-list/sci-fi/{0}/", script: "gen.js"},
        {title: "Drama", input: "/manga-list/drama/{0}/", script: "gen.js"},
        {title: "Seinen", input: "/manga-list/seinen/{0}/", script: "gen.js"},
        {title: "Ecchi", input: "/manga-list/Ecchi/{0}/", script: "gen.js"},
        {title: "Shoujo", input: "/manga-list/Shoujo/{0}/", script: "gen.js"},
        {title: "Fantasy", input: "/manga-list/Fantasy/{0}/", script: "gen.js"},
        {title: "Shojou Ai", input: "/manga-list/shojou-ai/{0}/", script: "gen.js"},
        {title: "Gender Bender", input: "/manga-list/Gender-Bender/{0}/", script: "gen.js"},
        {title: "Shounen", input: "/manga-list/Shounen/{0}/", script: "gen.js"},
        {title: "Harem", input: "/manga-list/Harem/{0}/", script: "gen.js"},
        {title: "Shounen Ai", input: "/manga-list/shounen-ai/{0}/", script: "gen.js"},
        {title: "Historical", input: "/manga-list/historical/{0}/", script: "gen.js"},
        {title: "Slice of Life", input: "/manga-list/slice-of-life/{0}/", script: "gen.js"},
        {title: "Horror", input: "/manga-list/Horror/{0}/", script: "gen.js"},
        {title: "Smut", input: "/manga-list/Smut/{0}/", script: "gen.js"},
        {title: "Josei", input: "/manga-list/Josei/{0}/", script: "gen.js"},
        {title: "Sports", input: "/manga-list/Sports/{0}/", script: "gen.js"},
        {title: "Live action", input: "/manga-list/live-action/{0}/", script: "gen.js"},
        {title: "Supernatural", input: "/manga-list/supernatural/{0}/", script: "gen.js"},
        {title: "Manhua", input: "/manga-list/Manhua/{0}/", script: "gen.js"},
        {title: "Tragedy", input: "/manga-list/Tragedy/{0}/", script: "gen.js"},
        {title: "Manhwa", input: "/manga-list/Manhwa/{0}/", script: "gen.js"},
        {title: "Adventure", input: "/manga-list/Adventure/{0}/", script: "gen.js"},
        {title: "Martial Art", input: "/manga-list/Martial-art/{0}/", script: "gen.js"},
        {title: "Yaoi", input: "/manga-list/Yaoi/{0}/", script: "gen.js"},
        {title: "Mature", input: "/manga-list/Mature/{0}/", script: "gen.js"},
        {title: "Raw", input: "/manga-list/raw/{0}/", script: "gen.js"},
    ])
}

// console.log([...document.querySelectorAll('.sub-menu .container li > a')].map(e => `{title: "${e.innerText.trim()}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '') + '/{0}/'}", script: "gen.js"},`).join('\n'));