function execute() {
    return Response.success([
        {title: "Truyện loạn luân", input: "/tag/truyen-sex-loan-luan/", script: "gen.js"},
        {title: "Truyện không loạn luân", input: "/tag/truyen-khong-loan-luan/", script: "gen.js"},
        {title: "Truyện sex có thật", input: "/tag/truyen-sex-co-that/", script: "gen.js"},
        {title: "Truyện sex ngoại tình", input: "/tag/truyen-sex-ngoai-tinh/", script: "gen.js"},
        {title: "Truyện sex hiếp dâm", input: "/tag/truyen-sex-hiep-dam/", script: "gen.js"},
        {title: "Truyện sex phá trinh", input: "/tag/truyen-sex-pha-trinh/", script: "gen.js"},
        {title: "Truyện sex bạo dâm", input: "/tag/truyen-sex-bao-dam/", script: "gen.js"},
        {title: "Truyện sex khổ dâm", input: "/tag/truyen-sex-kho-dam/", script: "gen.js"},
        {title: "Truyện sex cưỡng dâm", input: "/tag/truyen-sex-cuong-dam/", script: "gen.js"},
        {title: "Truyện NTR", input: "/tag/truyen-ntr/", script: "gen.js"},
        {title: "Truyện Cuckold", input: "/tag/truyen-sex-cuckold/", script: "gen.js"},
        {title: "Tâm sự bạn đọc", input: "/tag/tam-su-ban-doc/", script: "gen.js"},
        {title: "Cho người khác đụ vợ mình", input: "/tag/cho-nguoi-khac-du-vo-minh/", script: "gen.js"},
        {title: "Con gái thủ dâm", input: "/tag/con-gai-thu-dam/", script: "gen.js"},
        {title: "Đụ công khai", input: "/tag/du-cong-khai/", script: "gen.js"},
        {title: "Trao đổi vợ chồng", input: "/tag/trao-doi-vo-chong/", script: "gen.js"},
        {title: "Truyện les", input: "/tag/truyen-les/", script: "gen.js"},
        {title: "Thác loạn tập thể", input: "/tag/thac-loan-tap-the/", script: "gen.js"},
        {title: "Đụ tập thể", input: "/tag/du-tap-the/", script: "gen.js"},
        {title: "Làm tình tay ba", input: "/tag/lam-tinh-tay-ba/", script: "gen.js"},
        {title: "Dùng sextoys", input: "/tag/sextoy/", script: "gen.js"},
        {title: "Truyện sex tống tình", input: "/tag/truyen-sex-tong-tinh/", script: "gen.js"},
        {title: "Thuốc kích dục", input: "/tag/thuoc-kich-duc/", script: "gen.js"},
        {title: "Truyện sex mạnh", input: "/tag/truyen-sex-manh/", script: "gen.js"},
        {title: "Truyện sex nhẹ nhàng", input: "/tag/truyen-sex-nhe-nhang/", script: "gen.js"},
        {title: "Truyện bóp vú", input: "/tag/truyen-bop-vu/", script: "gen.js"},
        {title: "Truyện bú cặc", input: "/tag/truyen-bu-cac/", script: "gen.js"},
        {title: "Truyện bú lồn", input: "/tag/truyen-bu-lon/", script: "gen.js"},
        {title: "Truyện liếm đít", input: "/tag/truyen-liem-dit/", script: "gen.js"},
        {title: "Đụ lỗ đít", input: "/tag/du-lo-dit/", script: "gen.js"},
        {title: "Đụ thư ký", input: "/tag/du-thu-ky/", script: "gen.js"},
        {title: "Truyện sex học sinh", input: "/tag/truyen-sex-hoc-sinh/", script: "gen.js"},
        {title: "Truyện sex sinh viên", input: "/tag/truyen-sex-sinh-vien/", script: "gen.js"},
        {title: "Truyện sex cô giáo", input: "/tag/truyen-sex-co-giao/", script: "gen.js"},
        {title: "Bố chồng nàng dâu", input: "/tag/bo-chong-nang-dau/", script: "gen.js"},
        {title: "Bố đụ con gái", input: "/tag/bo-du-con-gai/", script: "gen.js"},
        {title: "Đụ mẹ ruột", input: "/tag/du-me-ruot/", script: "gen.js"},
        {title: "Đụ mẹ vợ", input: "/tag/du-me-vo/", script: "gen.js"},
        {title: "Đụ mẹ bạn", input: "/tag/du-me-ban/", script: "gen.js"},
        {title: "Vợ chồng", input: "/tag/vo-chong/", script: "gen.js"},
        {title: "Đụ vợ bạn", input: "/tag/du-vo-ban/", script: "gen.js"},
        {title: "Đụ chị gái", input: "/tag/du-chi-gai/", script: "gen.js"},
        {title: "Chị dâu em chồng", input: "/tag/chi-dau-em-chong/", script: "gen.js"},
        {title: "Làm tình với chị vợ", input: "/tag/lam-tinh-voi-chi-vo/", script: "gen.js"},
        {title: "Đụ em gái", input: "/tag/du-em-gai/", script: "gen.js"},
        {title: "Đụ em vợ", input: "/tag/du-em-vo/", script: "gen.js"},
        {title: "Đụ cháu gái", input: "/tag/du-chau-gai/", script: "gen.js"},
        {title: "Đụ bạn của người yêu", input: "/tag/du-ban-cua-nguoi-yeu/", script: "gen.js"},
        {title: "Làm tình với đồng nghiệp", input: "/tag/lam-tinh-voi-dong-nghiep/", script: "gen.js"},
        {title: "Đụ giúp việc", input: "/tag/du-giup-viec/", script: "gen.js"},
        {title: "Đụ với hàng xóm", input: "/tag/du-voi-hang-xom/", script: "gen.js"},
        {title: "Đụ cave", input: "/tag/du-cave/", script: "gen.js"},
        {title: "Bác sĩ y tá", input: "/tag/bac-si-y-ta/", script: "gen.js"},
        {title: "Đụ máy bay", input: "/tag/du-may-bay/", script: "gen.js"},
        {title: "Người và thú", input: "/tag/nguoi-va-thu/", script: "gen.js"},
        {title: "Đụ trên tàu", input: "/tag/du-tren-tau/", script: "gen.js"},
        {title: "Làm tình nơi công cộng", input: "/tag/lam-tinh-noi-cong-cong/", script: "gen.js"},
        {title: "Truyện teen", input: "/tag/truyen-teen/", script: "gen.js"},
        {title: "Truyện cổ trang", input: "/tag/truyen-co-trang/", script: "gen.js"},
        {title: "Truyện sex hay", input: "/tag/truyen-sex-hay/", script: "gen.js"},
        {title: "Dâm thư trung quốc", input: "/tag/dam-thu-trung-quoc/", script: "gen.js"},
        {title: "Truyện sắc hiệp", input: "/tag/truyen-sac-hiep/", script: "gen.js"},
        {title: "Kinh nghiệm làm tình", input: "/tag/kinh-nghiem-lam-tinh/", script: "gen.js"},
        {title: "Truyện ma quỷ", input: "/tag/truyen-sex-ma-quy/", script: "gen.js"},
        {title: "Truyện Tết", input: "/tag/truyen-tet/", script: "gen.js"},
        {title: "Truyện nonSEX (Không có cảnh sex)", input: "/truyen-nonsex/", script: "gen.js"},
        {title: "Truyện cũ", input: "/truyen-cu/", script: "gen.js"},
    ]);
}

// console.log([...document.querySelectorAll('body > div.logo2 > div:nth-child(36) a')].map(e => `{title: "${e.innerText}", input: "${e.href.replace(/^(?:\/\/|[^/]+)*/, '')}", script: "gen.js"},`).join('\n'));