function execute() {
	return Response.success([
		{ "title": "Anal", "input": "/tag/anal/page/{0}/", "script": "gen.js" },
		{ "title": "Big Breasts", "input": "/tag/big-breasts/page/{0}/", "script": "gen.js" },
		{ "title": "Blowjob", "input": "/tag/blowjob/page/{0}/", "script": "gen.js" },
		{ "title": "Full Color", "input": "/tag/full-color/page/{0}/", "script": "gen.js" },
		{ "title": "Uncensored", "input": "/tag/uncensored/page/{0}/", "script": "gen.js" },
		{ "title": "Sole Female", "input": "/tag/sole-female/page/{0}/", "script": "gen.js" },
		{ "title": "MILF", "input": "/tag/milf/page/{0}/", "script": "gen.js" },
		{ "title": "Paizuri", "input": "/tag/paizuri/page/{0}/", "script": "gen.js" },
		{ "title": "Schoolgirl Uniform", "input": "/tag/schoolgirl-uniform/page/{0}/", "script": "gen.js" },
		{ "title": "Defloration", "input": "/tag/defloration/page/{0}/", "script": "gen.js" },
		{ "title": "Nakadashi", "input": "/tag/nakadashi/page/{0}/", "script": "gen.js" },
		{ "title": "Swimsuit", "input": "/tag/swimsuit/page/{0}/", "script": "gen.js" },
		{ "title": "Ponytail", "input": "/tag/ponytail/page/{0}/", "script": "gen.js" },
		{ "title": "Twintails", "input": "/tag/twintails/page/{0}/", "script": "gen.js" },
		{ "title": "Exhibitionism", "input": "/tag/exhibitionism/page/{0}/", "script": "gen.js" },
		{ "title": "Lingerie", "input": "/tag/lingerie/page/{0}/", "script": "gen.js" },
		{ "title": "Harem", "input": "/tag/harem/page/{0}/", "script": "gen.js" },
		{ "title": "Bukkake", "input": "/tag/bukkake/page/{0}/", "script": "gen.js" },
		{ "title": "Maid", "input": "/tag/maid/page/{0}/", "script": "gen.js" },
		{ "title": "Catgirl", "input": "/tag/catgirl/page/{0}/", "script": "gen.js" },
		{ "title": "BBW", "input": "/tag/bbw/page/{0}/", "script": "gen.js" },
		{ "title": "Deepthroat", "input": "/tag/deepthroat/page/{0}/", "script": "gen.js" },
		{ "title": "Tankoubon", "input": "/tag/tankoubon/page/{0}/", "script": "gen.js" },
		{ "title": "Facesitting", "input": "/tag/facesitting/page/{0}/", "script": "gen.js" },
		{ "title": "Tanlines", "input": "/tag/tanlines/page/{0}/", "script": "gen.js" },
		{ "title": "Humiliation", "input": "/tag/humiliation/page/{0}/", "script": "gen.js" },
		{ "title": "Bathroom Sex", "input": "/tag/bathroom-sex/page/{0}/", "script": "gen.js" },
		{ "title": "Threesome", "input": "/tag/threesome/page/{0}/", "script": "gen.js" },
		{ "title": "FFM Threesome", "input": "/tag/ffm-threesome/page/{0}/", "script": "gen.js" },
		{ "title": "Licking", "input": "/tag/licking/page/{0}/", "script": "gen.js" },
		{ "title": "Imouto", "input": "/tag/imouto/page/{0}/", "script": "gen.js" },
		{ "title": "Cosplay", "input": "/tag/cosplay/page/{0}/", "script": "gen.js" },
		{ "title": "Time Stop", "input": "/tag/time-stop/page/{0}/", "script": "gen.js" },
		{ "title": "Assjob", "input": "/tag/assjob/page/{0}/", "script": "gen.js" },
		{ "title": "Pantyjob", "input": "/tag/pantyjob/page/{0}/", "script": "gen.js" },
		{ "title": "Rimjob", "input": "/tag/rimjob/page/{0}/", "script": "gen.js" },
		{ "title": "Footjob", "input": "/tag/footjob/page/{0}/", "script": "gen.js" },
		{ "title": "Double Penetration", "input": "/tag/double-penetration/page/{0}/", "script": "gen.js" },
		{ "title": "Triple Penetration", "input": "/tag/triple-penetration/page/{0}/", "script": "gen.js" }
	])
}