function execute() {
	return Response.success([
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=2&state=all", "title": "Action", "script": "gen.js" },
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=3&state=all", "title": "Adult", "script": "gen.js" },
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=4&state=all", "title": "Adventure", "script": "gen.js"},
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=6&state=all", "title": "Comedy", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=7&state=all", "title": "Cooking", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=9&state=all", "title": "Doujinshi", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=10&state=all", "title": "Drama", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=11&state=all", "title": "Ecchi", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=12&state=all", "title": "Fantasy", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=13&state=all", "title": "Gender bender", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=14&state=all", "title": "Harem", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=15&state=all", "title": "Historical", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=16&state=all", "title": "Horror", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=45&state=all", "title": "Isekai", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=17&state=all", "title": "Josei", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=44&state=all", "title": "Manhua", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=43&state=all", "title": "Manhwa", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=19&state=all", "title": "Martial arts", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=20&state=all", "title": "Mature", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=21&state=all", "title": "Mecha", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=22&state=all", "title": "Medical", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=24&state=all", "title": "Mystery", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=25&state=all", "title": "One shot", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=26&state=all", "title": "Psychological", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=27&state=all", "title": "Romance", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=28&state=all", "title": "School life", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=29&state=all", "title": "Sci fi", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=30&state=all", "title": "Seinen", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=31&state=all", "title": "Shoujo", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=32&state=all", "title": "Shoujo ai", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=33&state=all", "title": "Shounen", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=34&state=all", "title": "Shounen ai", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=35&state=all", "title": "Slice of life", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=36&state=all", "title": "Smut", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=37&state=all", "title": "Sports", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=38&state=all", "title": "Supernatural", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=39&state=all", "title": "Tragedy", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=40&state=all", "title": "Webtoons", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=41&state=all", "title": "Yaoi", "script": "gen.js" }, 
		{ "input": "https://mangakakalot.com/manga_list?type=latest&category=42&state=all", "title": "Yuri", "script": "gen.js" }
	])
}