function execute() {
    return Response.success([
        {title: "Action", input: "/browse/?genre=Action&results={0}&filter=views#", script: "gen.js"},
        {title: "Adult", input: "/browse/?genre=Adult&results={0}&filter=views", script: "gen.js"},
        {title: "Adventure", input: "/browse/?genre=Adventure&results={0}&filter=views", script: "gen.js"},
        {title: "Comedy", input: "/browse/?genre=Comedy&results={0}&filter=views", script: "gen.js"},
        {title: "Cooking", input: "/browse/?genre=Cooking&results={0}&filter=views", script: "gen.js"},
        {title: "Doujinshi", input: "/browse/?genre=Doujinshi&results={0}&filter=views", script: "gen.js"},
        {title: "Drama", input: "/browse/?genre=Drama&results={0}&filter=views", script: "gen.js"},
        {title: "Ecchi", input: "/browse/?genre=Ecchi&results={0}&filter=views", script: "gen.js"},
        {title: "Fantasy", input: "/browse/?genre=Fantasy&results={0}&filter=views", script: "gen.js"},
        {title: "Gender bender", input: "/browse/?genre=Gender%20bender&results={0}&filter=views", script: "gen.js"},
        {title: "Harem", input: "/browse/?genre=Harem&results={0}&filter=views", script: "gen.js"},
        {title: "Historical", input: "/browse/?genre=Historical&results={0}&filter=views", script: "gen.js"},
        {title: "Horror", input: "/browse/?genre=Horror&results={0}&filter=views", script: "gen.js"},
        {title: "Isekai", input: "/browse/?genre=Isekai&results={0}&filter=views", script: "gen.js"},
        {title: "Josei", input: "/browse/?genre=Josei&results={0}&filter=views", script: "gen.js"},
        {title: "Manhua", input: "/browse/?genre=Manhua&results={0}&filter=views", script: "gen.js"},
        {title: "Manhwa", input: "/browse/?genre=Manhwa&results={0}&filter=views", script: "gen.js"},
        {title: "Martial arts", input: "/browse/?genre=Martial%20arts&results={0}&filter=views", script: "gen.js"},
        {title: "Mature", input: "/browse/?genre=Mature&results={0}&filter=views", script: "gen.js"},
        {title: "Mecha", input: "/browse/?genre=Mecha&results={0}&filter=views", script: "gen.js"},
        {title: "Medical", input: "/browse/?genre=Medical&results={0}&filter=views", script: "gen.js"},
        {title: "Mystery", input: "/browse/?genre=Mystery&results={0}&filter=views", script: "gen.js"},
        {title: "One shot", input: "/browse/?genre=One%20shot&results={0}&filter=views", script: "gen.js"},
        {title: "Psychological", input: "/browse/?genre=Psychological&results={0}&filter=views", script: "gen.js"},
        {title: "Romance", input: "/browse/?genre=Romance&results={0}&filter=views", script: "gen.js"},
        {title: "School life", input: "/browse/?genre=School%20life&results={0}&filter=views", script: "gen.js"},
        {title: "Sci fi", input: "/browse/?genre=Sci%20fi&results={0}&filter=views", script: "gen.js"},
        {title: "Seinen", input: "/browse/?genre=Seinen&results={0}&filter=views", script: "gen.js"},
        {title: "Shoujo", input: "/browse/?genre=Shoujo&results={0}&filter=views", script: "gen.js"},
        {title: "Shounen", input: "/browse/?genre=Shounen&results={0}&filter=views", script: "gen.js"},
        {title: "Slice of life", input: "/browse/?genre=Slice%20of%20life&results={0}&filter=views", script: "gen.js"},
        {title: "Sports", input: "/browse/?genre=Sports&results={0}&filter=views", script: "gen.js"},
        {title: "Supernatural", input: "/browse/?genre=Supernatural&results={0}&filter=views", script: "gen.js"},
        {title: "Tragedy", input: "/browse/?genre=Tragedy&results={0}&filter=views", script: "gen.js"},
        {title: "Webtoons", input: "/browse/?genre=Webtoons&results={0}&filter=views", script: "gen.js"},
        {title: "ladies", input: "/browse/?genre=ladies&results={0}&filter=views", script: "gen.js"}
    ]);
}