function execute(){
    return Response.success([
        {input:"/genre/4-koma/",title:"4-koma",script:"gen.js"},
        {input:"/genre/action/",title:"Action",script:"gen.js"},
        {input:"/genre/adult/",title:"Adult",script:"gen.js"},
        {input:"/genre/adventure/",title:"Adventure",script:"gen.js"},
        {input:"/genre/comedy/",title:"Comedy",script:"gen.js"},
        {input:"/genre/cooking/",title:"Cooking",script:"gen.js"},
        {input:"/genre/crime/",title:"Crime",script:"gen.js"},
        {input:"/genre/drama/",title:"Drama",script:"gen.js"},
        {input:"/genre/ecchi/",title:"Ecchi",script:"gen.js"},
        {input:"/genre/fantasy/",title:"Fantasy",script:"gen.js"},
        {input:"/genre/gender-bender/",title:"Gender Bender",script:"gen.js"},
        {input:"/genre/gore/",title:"Gore",script:"gen.js"},
        {input:"/genre/harem/",title:"Harem",script:"gen.js"},
        {input:"/genre/historical/",title:"Historical",script:"gen.js"},
        {input:"/genre/horror/",title:"Horror",script:"gen.js"},
        {input:"/genre/isekai/",title:"Isekai",script:"gen.js"},
        {input:"/genre/josei/",title:"Josei",script:"gen.js"},
        {input:"/genre/lolicon/",title:"Lolicon",script:"gen.js"},
        {input:"/genre/martial-arts/",title:"Martial Arts",script:"gen.js"},
        {input:"/genre/mature/",title:"Mature",script:"gen.js"},
        {input:"/genre/mecha/",title:"Mecha",script:"gen.js"},
        {input:"/genre/medical/",title:"Medical",script:"gen.js"},
        {input:"/genre/music/",title:"Music",script:"gen.js"},
        {input:"/genre/music/",title:"Music",script:"gen.js"},
        {input:"/genre/mystery/",title:"Mystery",script:"gen.js"},
        {input:"/genre/philosophical/",title:"Philosophical",script:"gen.js"},
        {input:"/genre/psychological/",title:"Psychological",script:"gen.js"},
        {input:"/genre/romance/",title:"Romance",script:"gen.js"},
        {input:"/genre/school-life/",title:"School Life",script:"gen.js"},
        {input:"/genre/sci-fi/",title:"Sci-Fi",script:"gen.js"},
        {input:"/genre/seinen/",title:"Seinen",script:"gen.js"},
        {input:"/genre/shotacon/",title:"Shotacon",script:"gen.js"},
        {input:"/genre/shoujo/",title:"Shoujo",script:"gen.js"},
        {input:"/genre/shoujo-ai/",title:"Shoujo Ai",script:"gen.js"},
        {input:"/genre/shounen/",title:"Shounen",script:"gen.js"},
        {input:"/genre/shounen-ai/",title:"Shounen Ai",script:"gen.js"},
        {input:"/genre/slice-of-life/",title:"Slice of Life",script:"gen.js"},
        {input:"/genre/smut/",title:"Smut",script:"gen.js"},
        {input:"/genre/sports/",title:"Sports",script:"gen.js"},
        {input:"/genre/super-powers/",title:"Super Powers",script:"gen.js"},
        {input:"/genre/supernatural/",title:"Supernatural",script:"gen.js"},
        {input:"/genre/thriller/",title:"Thriller",script:"gen.js"},
        {input:"/genre/tragedy/",title:"Tragedy",script:"gen.js"},
        {input:"/genre/wuxia/",title:"Wuxia",script:"gen.js"},
        {input:"/genre/yaoi/",title:"Yaoi",script:"gen.js"},
        {input:"/genre/yuri/",title:"Yuri",script:"gen.js"}
    ])
}